### ISSUE TITLE
Download-Link destination in README wrong

### ISSUE THREAD

**Issue by codiflow** [gearsdigital/enhanced-toolbar-link-dialog#11]
It leads to https://github.com/gearsdigital/kirby-reporter/releases/latest instead of https://github.com/gearsdigital/enhanced-toolbar-link-dialog/releases

**Comment by gearsdigital** [comment]
@codiflow, thank you so much for bringing this up! I'll fix that immediately.

Children, that is the reason why you not copy and paste anything!
