### ISSUE TITLE
add plugin option to configure displayed title

### ISSUE THREAD

**Issue by bnomei** [gearsdigital/enhanced-toolbar-link-dialog#12]
could use an plugin option based on a query instead.
i would need that to show parent title as a category kind of style.

```
'gearsdigital.enhanced-toolbar-link-dialog.link.title' => '{{ page.title }} [ {{ page.parent.title }} ]',
```

https://github.com/gearsdigital/enhanced-toolbar-link-dialog/blob/master/index.php#L16
```php
$query = option('gearsdigital.enhanced-toolbar-link-dialog.link.title', '{{ page.title }}');
return Str::template($query, [
 'page' => $page,
 'site' => site(),
 'kirby' => kirby(),
]);
```

**Comment by gearsdigital** [comment]
Absolutely! I've limited time right now and I guess I will provide this feature by the end of next week. A pull request is very much appreciated 🙂

**Comment by gearsdigital** [comment]
@bnomei It took me a while but I finally added the suggested option to configure the displayed title. Would you mind to have a look at #18 ?
