### ISSUE TITLE
Add Open in a new tab? option toggle for External links

### ISSUE THREAD

**Issue by nicolasbulb** [gearsdigital/enhanced-toolbar-link-dialog#13]
I would be so nice to be able to add an Open in a new tab? option toggle for External links.

**Comment by gearsdigital** [comment]
Good morning @nicolasbulb, I'll have a look on that :)

**Comment by gearsdigital** [comment]
@nicolasbulb It took me quite a while but with version 1.3.0 you'll have the ability to specify a link target. You can expect a release within the next days.

<img width="1514" alt="Bildschirmfoto 2020-07-03 um 22 40 42" src="https://user-images.githubusercontent.com/965069/86496623-9285e980-bd7e-11ea-85d7-4d5e839f3f5d.png">
