### ISSUE TITLE
Issue when trying to use plugin in panel Tab

### ISSUE THREAD

**Issue by constantinjoly** [gearsdigital/enhanced-toolbar-link-dialog#14]
It seems that there is a bug if plugin is not used in the first page Tab. When try to click to internal link tab, it will redirect to the first page tab:

![GIF](https://user-images.githubusercontent.com/49160577/79722776-f69f2280-82e4-11ea-889a-7c693f4d6710.gif)

**Comment by gearsdigital** [comment]
Hi @constantinjoly, thats a good catch! Thank you very much for bringing this my attention 👍  I'll have a look later this week.

**Comment by gearsdigital** [comment]
@constantinjoly Thanks again for reporting this issue. It has now been fixed and will be released with version 1.3.0.
