### ISSUE TITLE
link target shows 2x _blank

### ISSUE THREAD

**Issue by CrisGraphics** [gearsdigital/enhanced-toolbar-link-dialog#20]
Sorry to bother again, but here's another (small) bug, that I've found.

**Describe the bug**
The label for 'self' in the dropdown shows 'blank'.

**Screenshot**
<img width="473" alt="target" src="https://user-images.githubusercontent.com/16305374/86570626-819cca00-bf70-11ea-9651-8d0516420f46.png">

**enhanced-toolbar-link-dialog Version**
1.3

**Kirby Version**
3.3.6

Also, maybe an enhancement could be to only show the insert button (or make it active), when a page has been selected, so the user can't insert `(link: null)`.
I'm very happy with Your plugin, and I already feel bad for the many reports, so let me know, how I can buy You a beer! 🙃

**Comment by gearsdigital** [comment]
@CrisGraphics It seems I owe you a couple of beers 🍻! Thank you so much for reporting all the issues!!!

I can confirm that issue and will fix it later today. The enhancement is also a great idea and will be added too :)
