### ISSUE TITLE
Activate insert button after selection

### ISSUE THREAD

**Issue by gearsdigital** [gearsdigital/enhanced-toolbar-link-dialog#21]
Only show the modal insert button (or make it active), when a page has been selected, so the user can't insert `(link: null)`.

**Comment by gearsdigital** [comment]
I decided not to change the `Ok-Button` behaviour. The reason is that the panel doesn't have such kind of functionality and I think that this would breal with the current Panel UI.

Instead I fixed the issue of `(link: null)` being inserted when the dialog gets closed via Ok but without any selection.

//cc @CrisGraphics

**Comment by CrisGraphics** [comment]
> I decided not to change the `Ok-Button` behaviour. The reason is that the panel doesn't have such kind of functionality and I think that this would breal with the current Panel UI.
> 
> Instead I fixed the issue of `(link: null)` being inserted when the dialog gets closed via Ok but without any selection.
> 
> //cc @CrisGraphics

Sorry, again I'm late to the party! Yes, You're right! 
I also noticed that the default Panel dialogue behaviour allows to insert an empty link tag, right after I made that suggestion -  so Your decision definitely makes more sense here!
Thanks @gearsdigital  for keeping it up to date! Have a great weekend! ✌🏼🙃
