### ISSUE TITLE
Internal link search not working

### ISSUE THREAD

**Issue by janherman** [gearsdigital/enhanced-toolbar-link-dialog#22]
I noticed Internal link search field is not working properly after updating to 1.3.1.

**To reproduce:**
1. open link dialog and switch to Internal link
2. start typing - no filter is applied and I get a lot of errors in console: `Uncaught TypeError: can't access property "page", c.pagination is undefined`

If I have more pages, so that pagination is displayed at the bottom, the search kind of works. I have to:
1. start typing - the view is not filtered again
2. click on next page in pagination
3. sometimes, the pages list in filtered according to the search term

**My setup:**
Kirby 3.4.0, Enhanced toolbar link dialog v. 1.3.1

**Comment by CrisGraphics** [comment]
I can confirm that issue.
Same setup

**Comment by gearsdigital** [comment]
Yeah, I can confirm that too. Thanks for reporting @janherman !

**Comment by CrisGraphics** [comment]
Many thanks for the effort Your put into this plugin and keeping it up to date!
All the best! 🍻🍻🍻
