### ISSUE TITLE
Make Link-Target Text in Dropdown configurable

### ISSUE THREAD

**Issue by CrisGraphics** [gearsdigital/enhanced-toolbar-link-dialog#33]
Here's another improvement, that could be useful. 
Sometimes there are Editors that have absolutely no idea what "target:" self, blank, top, etc means.
So instead of hardcoding the text into select field, we could extend the options in the config with a custom text, like

```
"blank" => "Open in new window / tab",
"self" => "Open in same window",
"top" ...
```

I don't want to bother You too much, so I can try to solve it myself and make a pull request again (will probably find some time next week).
Just wanted to know, what You think about the idea. :)

**Comment by gearsdigital** [comment]
That is actually a very good idea @CrisGraphics. Many Thanks!
