### ISSUE TITLE
Enable link dialog in Kirby Editor

### ISSUE THREAD

**Issue by henninghorn** [gearsdigital/enhanced-toolbar-link-dialog#34]
Great plugin! Really helps lower the barrier for non-technical editors.

Is there anyway to trigger the plugin's link dialog when adding a link within the [Kirby Editor](https://github.com/getkirby/editor)? Unfortunately when you mark a text and want to add/convert it to a link, you get the standard link dialog.

I have tried to read through the plugin's code, but I can't see where the hook for the default textarea field is, and therefore I do not know how to hook into the Kirby Editor plugin.

Happy to give it a shot myself!

**Comment by gearsdigital** [comment]
Hi @henninghorn, I very appreciate your feedbak 👍 

It's true, this Plugin isn't compatible to the Kirby Editor. This question was asked before in the Kirby Forums and but I haven't had time to take a deeper look onto the Editor but I'ld probably start here: https://github.com/getkirby/editor/blob/5e6263a0e660932490133790af1c12e4d8d9e509/src/components/ProseMirror/ProseMirror.vue#L51 and here https://github.com/getkirby/editor/blob/5e6263a0e660932490133790af1c12e4d8d9e509/src/components/ProseMirror/Dialogs/Link.vue.

**Comment by gearsdigital** [comment]
I'll close this issue because the Kirby Editor is now EOL and has been archived by the owner.
