### ISSUE TITLE
Translation Dutch (NL)

### ISSUE THREAD

**Issue by morrits** [gearsdigital/enhanced-toolbar-link-dialog#36]
$translations = [
    'nl' => [
        'gearsdigital.enhanced-toolbar-link-dialog.internal' => 'Interne Link',
        'gearsdigital.enhanced-toolbar-link-dialog.external' => 'Externe Link',
        'gearsdigital.enhanced-toolbar-link-dialog.empty' => 'Geen pagina's gevonden',
        'gearsdigital.enhanced-toolbar-link-dialog.target.title' => 'Link Doel',
        'gearsdigital.enhanced-toolbar-link-dialog.target.help' => 'Geef aan waar het gekoppelde document moet worden geopend.',
    ],

**Comment by morrits** [comment]
Sorry don't know yet how to do a pull request!

**Comment by gearsdigital** [comment]
Awesome 🥳  

I'll add this for you and prepare a new release later this day.
