### ISSUE TITLE
Compatibility issue with Kirby 3.6.0 alpha.x

### ISSUE THREAD

**Issue by zeljkovorel** [gearsdigital/enhanced-toolbar-link-dialog#49]
Hello everyone,
with new Kirby version "3.6.0 alpha.x" the page listing under INTERNER LINK isn't visible anymore.
Also German Language setting is not reflected anymore.
Last known running plug-in is with Kirby version "3.5.7.1" 

I see:
![image](https://user-images.githubusercontent.com/88711468/130231052-b6fe637f-6d69-492c-bb77-e7dfe4b179b3.png)

instead of:
![image](https://user-images.githubusercontent.com/88711468/130231440-a0e02a11-14aa-4ad3-8471-153276cdf031.png)

Best Regards
Zeljko

**Comment by gearsdigital** [comment]
Thanks for reporting! I'll have a look once I've completed the refactoring of my kirby-reporter plugin.
