### ISSUE TITLE
Internal Links should be converted to relative links

### ISSUE THREAD

**Issue by Maybach91** [gearsdigital/enhanced-toolbar-link-dialog#50]
Is it possible to have links within a textarea to be relative instead of absolute?

```
(link: /neues/a-night-in-the-forest text: I am the link)
```

this gives me a with `$page->text()->kt()` the following:
```html
<a href=\"http://fulldomain.de/neues/a-night-in-the-forest\">I am the link</a>
```

If its a internal link, i want to get the following:
```html
<a href=\"./neues/a-night-in-the-forest\">I am the link</a>
```

It works, if i change the link field in my textarea to the following:
```html
(link: ./neues/a-night-in-the-forest text: I am the link)
```

**Comment by gearsdigital** [comment]
Hello @Maybach91 sorry for the late response and thank you very much for your feedback! I'll have a look on that.

**Comment by gearsdigital** [comment]
I'am not entirely that I understood your use-case correctly @Maybach91. What is your expectation here? Why do you need relative URLs?

**Comment by Maybach91** [comment]
> I'am not entirely sure that I understood your use-case correctly @Maybach91. What is your expectation here? Why do you need relative URLs? Usually I recommend to use absolute URLs which makes the (my) life easier ^^
> 
> I'm asking because I need to figure out this: The link should be "relative" to what? The current active panel page?

Thanks for getting back to me! I set my base url to `/`. Which leads to have the absolute links set to `https://domain.com/https://domain.com/posts/lorem-ipsum` which fails to redirect. Maybe i have to find a workaround for this on my end. 🤔

**Comment by gearsdigital** [comment]
I guess it would probably easier to handle it on your side - maybe a simple str_replace could do the trick?

**Comment by gearsdigital** [comment]
I'm going to close this issue for now. If you want we can try to work something out. Just let me know :)
