### ISSUE TITLE
Optimize user interface

### ISSUE THREAD

**Issue by gearsdigital** [gearsdigital/enhanced-toolbar-link-dialog#55]
It would be nice the clean up the UI bit by removing the "Target" dropdown and get rid of "Frame" option. Maybe a simple checkbox or toggle field could do the trick.

**Comment by herrajon** [comment]
@gearsdigital 

I absolutely agree. I know both the people that still use the Frameset today. Most of the year they are without the Internet measuring wind speed in Jan Mayen.

A few observations:

1) Remove those frame options
2) Replace id with a checkbox/toggle field for new window/tab (target="_blank")
3) Add the new window option also and more importantly to the External link part.

As a rule of thumb I believe: External links open in a new tab; Internal links in the same tab.

4) Adding a **rel** attribute for the links for SEO purposes. This is a nice to have but a bit crucial if your are going to do your SEO properly. A food for thought.
5) The anchor option is a nice to have. Not sure how many use it though. Perhaps enabling it in the config.php would be an option. 
5.1) Instruct how (with the hashtag or not #) the user should enter its anchor element or clean it.
6) Increase the default number of pages to say ten. It is now five and very easy to increase it in the config.php
7) Also I suggest giving the title field more space. The whole width as title tend to be longer than the twenty chars it displays now. Also add it to the External part.

If possible to skip things I say do it. Cleaner interface is always more usable and enjoyable. And the Defaults should be best.

End of rant.

Thanks for that ravishing plugin @gearsdigital.
-j

**Comment by gearsdigital** [comment]
Thank you very much for your input! I'll figure something out.
