### ISSUE TITLE
Deprecation Warning with php 8.1.3

### ISSUE THREAD

**Issue by CrisGraphics** [gearsdigital/enhanced-toolbar-link-dialog#60]
Hi Steffen,

I'm getting the following deprecation warning when I log in to the panel:
`is_a(): Passing null to parameter #2 ($class) of type string is deprecated"`.
I went through all installed plugins and it seems, that the warning comes from the toolbar-link-dialog.
I recently upgraded my php version, so I guess, that's why the error shows up now.

Toolbar Version: 2.2.2
Kirby Version: 3.6.3-rc.1
PHP Version: 8.1.3

**Comment by gearsdigital** [comment]
Hi Chris, thanks for reaching out! So sorry to hear that ☹️

I haven't yet tested this plugin with PHP 8 and sadly no time to fix that. I guess this is only a warning... As a workaround you could set `error_reporting(E_ALL ^ E_WARNING)` which  enables all error reportings besides warnings.

**Comment by gerricom** [comment]
The reason is, that the `type` of the defined model is `null`: https://github.com/gearsdigital/enhanced-toolbar-link-dialog/blob/main/index.php#L153

But... what is valid value? I tried setting it to `simplepagemodel` and this works... but I'm not sure, if it is intended to be?

**Comment by gearsdigital** [comment]
@gerricom I've no clue either 🙈 I didn't fully understand the simplepagemodel intially. I'll try to have a look on that topic within the next days.

**Comment by gearsdigital** [comment]
Hey @CrisGraphics, I just wanted to let you know that I've fixed the issue – as @gerricom pointed out, it is the missing `type`. Setting  it to `collection` seems to resolve it, but setting it to anything else like `simplepagemodel` or `''` works too. So the question stays: _What is a valid model type_?

Ommiting the `type` results in:

```
Exception: Whoops\Exception\ErrorException
    Undefined array key "type" 
```

Setting type to null results in:

```
Exception: Whoops\Exception\ErrorException
    is_a(): Passing null to parameter #2 ($class) of type string is deprecated 
```

Maybe @lukasbestle  or @bastianallgeier can help out here and point me in the right direction?

**Comment by gearsdigital** [comment]
@gerricom @CrisGraphics This issue is resolved now. Sorry for delay 😜
