### ISSUE TITLE
Pages don't show up in 3.7

### ISSUE THREAD

**Issue by trych** [gearsdigital/enhanced-toolbar-link-dialog#67]
Hi there!

In Kirby v3.7, the paginated list of pages does not show up anymore which does not allow for the selection of pages and effectively renders the plugin unusable.

![20220725-165500_Screenshot_starterkit test](https://user-images.githubusercontent.com/9803905/180807279-4a3d1ea8-656c-4357-b19e-51c2ef756c1c.png)

Note that the filtering and searching still seems to work as indicated by the pagination numbers and UI, but I cannot select any pages anymore. Any idea how to fix this?

Thanks!

**Comment by gearsdigital** [comment]
I am very sorry @trych. Haven't found time to make this plugin comptaible to Kirby 3.7 🙈 Are there any errors reportted to the error log or browser console?

What happens is that the Dialog makes a request to [this route](https://github.com/gearsdigital/enhanced-toolbar-link-dialog/blob/96708bd9c4f0f2072289f885f4c9000304e03c22/index.php#L181).  Maybe this is a starting point?!

**Comment by Maybach91** [comment]
> I am very sorry @trych. Haven't found time to make this plugin comptaible to Kirby 3.7 🙈 Are there any errors reported to the error log or browser console?
> 
> What happens is that the Dialog makes a request to [this route](https://github.com/gearsdigital/enhanced-toolbar-link-dialog/blob/96708bd9c4f0f2072289f885f4c9000304e03c22/index.php#L181) where a paged collection is created. Maybe this is a starting point?!

I’ve got the same error. The `/pages` endpoints response is successful and looks good to me:

<details>
<summary><code>/api/enhanced-toolbar-link-dialog/pages?page=1</code> Response:</summary>

```json
{
  "code": 200,
  "data": [
    {
      "id": "karriere/ausbildung-zur-veranstaltungskaufrau-oder-kaufmann",
      "slug": "/karriere/ausbildung-zur-veranstaltungskaufrau-oder-kaufmann",
      "title": "### Ausbildung zur veranstaltungskaufrau oder -kaufmann ###"
    },
    ...
  ],
  "pagination": {
    "page": 1,
    "total": 95,
    "offset": 0,
    "limit": 5
  },
  "status": "ok",
  "type": "collection"
}
```

</details>

There are no Console Errors or Request Errors. Here you can see the successful console logs of your app:
https://app.birdeatsbug.com/sessions/MaXNWDh6dvJTF_vxAjkgEImkr43UYLf1-GRVV-UK_NBD

**Comment by gearsdigital** [comment]
Thank you @Maybach91! It seems to be related to [`k-items/k-items`](https://getkirby.com/docs/reference/plugins/ui/items) which are used to render the list of pages within the modal. I'm currently working on that topic 🥳

**Comment by Maybach91** [comment]
> Thank you @Maybach91! It seems to be related to [`k-items/k-items`](https://getkirby.com/docs/reference/plugins/ui/items) which are used to render the list of pages within the modal. I'm currently working on that topic 🥳

@gearsdigital nice! thank you! i just installed a 3.6.6 (working) and the response of the API Call is exact the same.. (same structure etc). just to let you know :)

**Comment by gearsdigital** [comment]
Wish me luck ^^

**Comment by gearsdigital** [comment]
@trych @Maybach91 I was able to resolve this issue by removing the `k-items`-Component. I haven't spent too much time to investigate why it broke. I simply removed it. Anyhow, works again.

Thank you very much for your patience!

**Comment by trych** [comment]
@gearsdigital Thanks a lot, much appreciated!
