### ISSUE TITLE
Invalid model type "Kirby\Cms\Page" expected: "Page"

### ISSUE THREAD

**Issue by metakolor** [gearsdigital/enhanced-toolbar-link-dialog#71]
Kirby 3.7.1
enhanced-toolbar-link-dialog 2.2.3

Pops up right after opening the link-modal.
<img width="481" alt="screenshot" src="https://user-images.githubusercontent.com/60016398/183130050-86d090a2-4192-43eb-80e6-08eb0641e5d5.png">

**Comment by gearsdigital** [comment]
Sigh... 😵‍💫 Thanks @metakolor. I'll have a look!

**Comment by gearsdigital** [comment]
@metakolor I'm not able to reproduce this using the [Starterkit](https://github.com/getkirby/starterkit) as base 🧐

Can you to change line 152 in the plugin index.php to this?

```diff
'api' => [
        'models' => [
            'simplepagemodel' => [
-                'type' => 'Kirby\Cms\Page',
+                'type' => '\Kirby\Cms\Page',
```

**Comment by metakolor** [comment]
This worked for me, thank you!

**Comment by gearsdigital** [comment]
Awesome! I'll release a fix then... Thank you very much for reaching out!
