### ISSUE TITLE
Feature request: Option to disable the anchor field

### ISSUE THREAD

**Issue by arnaudjuracek** [gearsdigital/enhanced-toolbar-link-dialog#82]
First of all, thank you for your plugin. It is so simple that I may use it by default on all my new Kirby projects, until it ends up being eventually integrated to the Kirby core.

It would be really nice to have a config option to disable the anchor field, to allow building simpler websites for unskilled clients who do not need to know what an anchor is.

**Comment by gearsdigital** [comment]
You are very welcome @arnaudjuracek! Glad you find my plugin useful 🙏🏻

I like your idea and I'm going to implement this not only for the anchor, but also for every other field. It's a bit more challenging to keep the layout consistent. Not every field takes the full width, but I'm confident to find a proper solution :)

**Comment by arnaudjuracek** [comment]
IMHO the UX is better for the user when the field is completely hidden, but you may have other scenarios in mind where disabling the field makes more sense ?

Thanks for your time.

**Comment by gearsdigital** [comment]
Okay, let's do both ^^ The user can decide wether he wants to `disable` or `hide` a field. Thanky for your input!

**Comment by gearsdigital** [comment]
@arnaudjuracek Let me know if this feature works for you :)
