### ISSUE TITLE
Not compatible with latest Kirby release anymore

### ISSUE THREAD

**Issue by chrfickinger** [gearsdigital/enhanced-toolbar-link-dialog#83]
Kirby removed the DS constant. It was no longer used in Kirby 3 and only kept for backwards-compatibility with Kirby 2.
(see: https://github.com/getkirby/kirby/releases/tag/3.8.0-rc.1)

**Comment by gearsdigital** [comment]
Thanks @chrfickinger! I'll have an eye on that...
