### ISSUE TITLE
Impact on kirby modal height

### ISSUE THREAD

**Issue by batgithub** [gearsdigital/enhanced-toolbar-link-dialog#84]
Hi, thanks for your plugin that add a really good feature to kirby 🙂.

My issue is that your plugin impact the height of the general modal  of kirby (for changing status, name ...)

I found that there is a min-height:  in `EnhancedToolbarWriterLinkDialog.vue` that may cause this issue.
`
.k-dialog-body form {
	min-height: 340px;
}
`
Is there any reason to add this ? Because without this property it seems to work too ?

How it looks normally
![Capture d’écran 2023-03-09 à 13 11 25](https://user-images.githubusercontent.com/4511699/224019515-714db456-a6ba-45c6-9187-740d6ed54e17.png)

how it's altered by the plugin
![Capture d’écran 2023-03-09 à 13 08 35](https://user-images.githubusercontent.com/4511699/224018757-81db4045-94d1-41fe-99f8-9f18467d5367.png)

**Comment by gearsdigital** [comment]
@batgithub It's been a while... Sorry mate! 🙈 Anyhow, thank you very much for bringing this to my attention.

Pretty sure there was a reason once but to be honest, I can't remember ^^ It seems everything works as expected despite I've removed the conflicting styles. 

I guess that was a quick win?
