### ISSUE TITLE
Relative Links don't work with Subpages

### ISSUE THREAD

**Issue by CrisGraphics** [gearsdigital/enhanced-toolbar-link-dialog#9]
Unfortunately the links to subpages don't work now.
Maybe You could have a look into that.
Thank You! =)
![test](https://user-images.githubusercontent.com/16305374/73132431-5a35ee80-401b-11ea-9cf8-585b6734c788.gif)

**Comment by gearsdigital** [comment]
Thank you very much for bringing this up @CrisGraphics! I'll have a look on that and provide fix soo.
